export const authUserPassword  = '/api/authentication/username-password';
export const appliedJobs = '/api/candidates/appliedJobs';
export const desiredJobs = '/api/candidates/desiredJobs';
export const education = '/api/candidates/educations';
export const exprience = '/api/candidates/experiences';
export const jobActive = '';
export const fullProfile = '/api/candidates/profile';
export const personalInfo = '/api/candidates/personalInfo';
export const putDescription = '/api/candidates/description';
export const skillsController = '/api/candidates/skills';
export const languageSkillsController = '/api/candidates/languageSkills';
export const educationController= '/api/candidates/educations'
export const experienceController = '/api/candidates/experiences';
export const isLookingFobJobState = '/api/candidates/isLookingForJob/';
export const updateAvatar = '/api/candidates/avatar';
export const registrasionController = '/api/candidates/registration/email';
export const candidateAppliedJobController ='/api/candidates/appliedJobs';
export const saveJobController = '/api/candidates/savedJobs';
export const jobController = '/api/candidates/jobs';
export const notiController = '/api/candidates/notifications'